version: '3'
services:
#  handbrake:
#    container_name: handbrake
#    image: jlesage/handbrake:v1.22.4
#    environment:
#      - TZ=Europe/Dublin
#    ports:
#      - "5800:5800"
#    volumes:
#      - "./config/handbrake:/config:rw"
#      - "/home/dashford/io/handbrake/output/raw:/output:rw"
#      - "$HOME:/storage:ro"
#
#  makemkv:
#    container_name: makemkv
#    image: jlesage/makemkv:v1.17.0
#    environment:
#      - MAKEMKV_KEY=${MAKEMKV_KEY}
#      - TZ=Europe/Dublin
#    ports:
#      - "5700:5800"
#    volumes:
#      - "./config/makemkv:/config:rw"
#      - "/home/dashford/io/makemkv/output/raw:/output:rw"
#      - "$HOME:/storage:ro"
#    devices:
#      - "/dev/sr0:/dev/sr0"
#      - "/dev/sg2:/dev/sg2"

  sonarr:
    container_name: sonarr
    image: hotio/sonarr:latest
    ports:
      - "8989:8989"
    volumes:
      - sonarr:/config

  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:version-3.00-r0
    environment:
      - TZ=Europe/Dublin
      - USER=${TM_USER}
      - PASS=${TM_PASS}
      - PUID=1000
      - PGID=1000
    volumes:
      - transmission:/config
      - "/home/dashford/io/transmission/downloads:/downloads"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"


volumes:
  sonarr:
    driver: local
  transmission:
    driver: local